### PR TITLE
Don't embed subresource preload header when nginx failed to fetch

### LINKED ISSUE #35: Link rel=preload headers lacking integrity should be omitted
Chromium will recursively prefetch any `link`s from their origin unless `allowed-alt-sxg` and `alternate` are also specified. Thus, such links impede the privacy-preserving prefetch use case.

invoke_subrequests: https://github.com/google/nginx-sxg-module/blob/56e75562f227c838d4a2a53efd290e16f67504bb/ngx_http_sxg_filter_module.c#L334-L335 should modify the original `link` header to exclude any `rel=preload`s for which integrity cannot be obtained, per subresource_fetch_handler: https://github.com/google/nginx-sxg-module/blob/56e75562f227c838d4a2a53efd290e16f67504bb/ngx_http_sxg_filter_module.c#L274

(I'm not sure the best way to do that. I assume if the modification happens inside subresource_fetch_handler, it'll need to be protected by a mutex.)

### PR DESCRIPTION
**Pull request by kumagi**
fix #35 
All `link: rel="preload">` subresource should include `allowed-alt-sxg` entry with integrity to preserve privacy.

TODO: add some test.

### CODE REVIEW

File: ngx_http_sxg_filter_module.c [hunk 1]
```diff
@@ -303,38 +326,114 @@ static ngx_str_t extract_angled_url(char* str, size_t len) {
...
+                        &new_preload->as);
+        }
       }
       param += param_tail + 1;
     }
+    if (!found) {
+      if (non_preload_headers->len > 0) {
+        concat_str(non_preload_headers, ",", 1, r->pool);
+      }
+      concat_str(non_preload_headers, str, tail, r->pool);
```
Comment (gaul) [inline ngx_http_sxg_filter_module.c:387]: How many headers do you expect to have?  This has O(n**2) behavior due to the allocations and memcpy.  Maybe better to accumulate an `ngx_array_t` and create a single string after the loop?  Or loop twice, once getting the length and against copying the bytes, like `vsnprintf` does.

File: ngx_http_sxg_filter_module.c [hunk 2]
```diff
@@ -271,12 +278,28 @@ static ngx_int_t subresource_fetch_handler(ngx_http_request_t* req, void* data,
...
-    if (calc_integrity(req, &integrity) &&
-        sxg_write_string("<https://", &new_header_entry) &&
+    // Searches 'as' statement of original link header.
+    ngx_str_t as;
+    ngx_array_t* subresource_list = &ctx->subresource_list;
+    ngx_subresource_t* subresource = subresource_list->elts;
+    for (int i = 0; i < subresource_list->nelts; ++i) {
+      if (ngx_strncmp(subresource[i].url.data, req->uri.data,
+                      subresource[i].url.len) == 0) {
+        as = subresource[i].as;
```
Comment (gaul) [inline ngx_http_sxg_filter_module.c:288]: `break`?

File: ngx_http_sxg_filter_module.c [hunk 3]
```diff
@@ -271,12 +278,28 @@ static ngx_int_t subresource_fetch_handler(ngx_http_request_t* req, void* data,
     sxg_buffer_t integrity = sxg_empty_buffer();
     sxg_buffer_t new_header_entry = sxg_empty_buffer();
 
-    if (calc_integrity(req, &integrity) &&
-        sxg_write_string("<https://", &new_header_entry) &&
+    // Searches 'as' statement of original link header.
+    ngx_str_t as;
```
Comment (gaul) [inline ngx_http_sxg_filter_module.c:282]: Initialize to `NULL`?

File: ngx_http_sxg_filter_module.c (hunk 2 above)
Comment (kumagi) [reply ngx_http_sxg_filter_module.c:294]: Done.

File: ngx_http_sxg_filter_module.c (hunk 3 above)
Comment (kumagi) [reply ngx_http_sxg_filter_module.c:288]: Done.

File: ngx_http_sxg_filter_module.c [hunk 4]
```diff
@@ -266,17 +273,39 @@ static ngx_int_t subresource_fetch_handler(ngx_http_request_t* req, void* data,
...
+    ngx_array_t* subresource_list = &ctx->subresource_list;
+    ngx_subresource_t* subresource = subresource_list->elts;
+    for (int i = 0; i < subresource_list->nelts; ++i) {
+      if (ngx_strncmp(subresource[i].url.data, req->uri.data,
+                      subresource[i].url.len) == 0) {
+        as = subresource[i].as;
+      }
+    }
+
+    if (as.len > 0 && sxg_write_string("<https://", &new_header_entry) &&
```
Comment (gaul) [inline ngx_http_sxg_filter_module.c:298]: Should this check `as != NULL`?

Comment (kumagi) [reply ngx_http_sxg_filter_module.c:298]: No, `as` is a structure consist of `data` and `len`. It is not a pointer, so comparing against `NULL` is not good way.

File: ngx_http_sxg_filter_module.c (hunk 1 above)
Comment (kumagi) [reply ngx_http_sxg_filter_module.c]: OK, I modified the function to work in 2 modes, estimation only and actual write. First run this function in estimation mode and get the expected memory length, and allocate and do actual write.

File: ngx_http_sxg_filter_module.c [hunk 5]
```diff
@@ -303,38 +333,123 @@ static ngx_str_t extract_angled_url(char* str, size_t len) {
...
+  ngx_table_elt_t* v = part->elts;
+
+  for (int i = 0; i < part->nelts; i++) {
+    if (strncasecmp(kAccept, (const char*)v[i].key.data, strlen(kAccept)) ==
+            0 &&
+        !set_str(req->pool, &v[i].value, accept)) {
+      return false;
+    }
+  }
+  return true;
```
Comment (twifkak) [inline ngx_http_sxg_filter_module.c:445]: Do we need to append an accept header if none is found, or will that never happen?

File: ngx_http_sxg_filter_module.c [hunk 6]
```diff
@@ -303,38 +333,123 @@ static ngx_str_t extract_angled_url(char* str, size_t len) {
...
+      extract_preload_url_list(link, NULL, NULL, req);
+  non_preload_headers->data = ngx_palloc(req->pool, non_preload_headers_len);
+  non_preload_headers->len = non_preload_headers_len;
+  extract_preload_url_list(link, urls, non_preload_headers, req);
   return urls;
 }
 
+static bool set_str(ngx_pool_t* pool, ngx_str_t* dst, const char* src) {
+  const size_t len = strlen(src);
+  dst->data = ngx_palloc(pool, len);
```
Comment (twifkak) [inline ngx_http_sxg_filter_module.c:423]: Do we need to [`ngx_pfree()`](https://www.nginx.com/resources/wiki/extending/api/alloc/#ngx-pfree) the old value if non-NULL?

File: ngx_http_sxg_filter_module.c [hunk 7]
```diff
@@ -303,38 +333,123 @@ static ngx_str_t extract_angled_url(char* str, size_t len) {
   return (ngx_str_t){.data = NULL, .len = 0};
 }
 
-static void extract_preaload_url_list(ngx_str_t* link, ngx_array_t* const dst,
-                                      ngx_http_request_t* r) {
+// TODO(kumagi): Complex logic should be migrated to ngx_sxg_utils.c.
```
Comment (gaul) [inline ngx_http_sxg_filter_module.c:336]: This logic is complex -- can you unit test this?

File: ngx_http_sxg_filter_module.c [hunk 8]
```diff
@@ -303,38 +333,123 @@ static ngx_str_t extract_angled_url(char* str, size_t len) {
...
-        ngx_str_t* const new_url = ngx_array_push(dst);
-        *new_url = url;
-        break;
+        if (dst != NULL) {
+          new_preload = ngx_array_push(dst);
+          new_preload->url.data = ngx_palloc(r->pool, url.len);
+          new_preload->url.len = url.len;
+          ngx_memcpy(new_preload->url.data, url.data, url.len);
+          while (new_preload->url.data[new_preload->url.len - 1] == ' ') {
+            new_preload->url.len--;
```
Comment (gaul) [inline ngx_http_sxg_filter_module.c:366]: Should this also write `'\0'` to truncate the string?  Or does the call to `ngx_strncmp` using `url.len` suffice?

File: ngx_http_sxg_filter_module.c [hunk 9]
```diff
@@ -266,17 +273,40 @@ static ngx_int_t subresource_fetch_handler(ngx_http_request_t* req, void* data,
...
     sxg_buffer_t integrity = sxg_empty_buffer();
     sxg_buffer_t new_header_entry = sxg_empty_buffer();
 
-    if (calc_integrity(req, &integrity) &&
-        sxg_write_string("<https://", &new_header_entry) &&
+    // Searche 'as' statement of original link header.
+    ngx_str_t as = ngx_null_string;
+    ngx_array_t* subresource_list = &ctx->subresource_list;
+    ngx_subresource_t* subresource = subresource_list->elts;
+    for (int i = 0; i < subresource_list->nelts; ++i) {
```
Comment (twifkak) [inline ngx_http_sxg_filter_module.c:291]: It looks like this is `O(nelts^2)` given [the outer for loop](https://github.com/google/nginx-sxg-module/blob/1da319d87b99ab84653d4668018b22aac5e8808c/ngx_http_sxg_filter_module.c#L454). Am I reading that right? If so, this is probably fine because it's expected to be small (<20?), and the contents of this loop are fast, but maybe we should leave a TODO or open a bug.

File: ngx_http_sxg_filter_module.c [hunk 10]
```diff
@@ -266,17 +273,40 @@ static ngx_int_t subresource_fetch_handler(ngx_http_request_t* req, void* data,
...
+      if (ngx_strncmp(subresource[i].url.data, req->uri.data,
+                      subresource[i].url.len) == 0) {
+        as = subresource[i].as;
+        break;
+      }
+    }
+
+    if (as.len > 0 && sxg_write_string("<https://", &new_header_entry) &&
+        buffer_write_str_t(&cscf->server_name, &new_header_entry) &&
+        buffer_write_str_t(&req->uri, &new_header_entry) &&
```
Comment (twifkak) [inline ngx_http_sxg_filter_module.c:301]: Do we need to append `"?" +` [`req->args`](https://www.nginx.com/resources/wiki/extending/api/http/#c.ngx_http_request_t.args) too?

File: ngx_http_sxg_filter_module.c [hunk 11]
```diff
@@ -408,6 +530,7 @@ static ngx_int_t ngx_http_sxg_header_filter(ngx_http_request_t* req) {
         invoke_subrequests(&value[i].value, req, ctx);
       }
     }
+    value->value = ctx->link_header;
```
Comment (twifkak) [inline ngx_http_sxg_filter_module.c:533]: Should this be inside the `if` at line 530? Currently, it looks like it would overwrite every header value with the list non-preload links.

File: ngx_http_sxg_filter_module.c [hunk 12]
```diff
@@ -303,38 +333,123 @@ static ngx_str_t extract_angled_url(char* str, size_t len) {
...
+        if (dst != NULL) {
+          new_preload = ngx_array_push(dst);
+          new_preload->url.data = ngx_palloc(r->pool, url.len);
+          new_preload->url.len = url.len;
+          ngx_memcpy(new_preload->url.data, url.data, url.len);
+          while (new_preload->url.data[new_preload->url.len - 1] == ' ') {
+            new_preload->url.len--;
+          }
+          if (as.data != NULL) {
+            new_preload->as = as;
```
Comment (twifkak) [inline ngx_http_sxg_filter_module.c:369]: Why is this here? It seems this may erroneously copy forward the `as` from a previous link on line 374, and this case is already handled by line 376.

File: ngx_http_sxg_filter_module.c [hunk 13]
```diff
@@ -303,38 +333,123 @@ static ngx_str_t extract_angled_url(char* str, size_t len) {
...
+          }
+        }
+        found = true;
+      }
+      if (param_is_as(param, param_tail, (const char**)&as.data, &as.len)) {
```
Comment (twifkak) [inline ngx_http_sxg_filter_module.c:374]: Should this be inside the above `if (param_is_preload(...))`? Otherwise, I think there is a chance it would set `as` on the wrong `new_preload`, e.g. for a header like:

```
Link: <foo>;rel=preload,<bar>;as=image
```

File: ngx_http_sxg_filter_module.c [hunk 14]
```diff
@@ -303,38 +333,123 @@ static ngx_str_t extract_angled_url(char* str, size_t len) {
   return (ngx_str_t){.data = NULL, .len = 0};
 }
 
-static void extract_preaload_url_list(ngx_str_t* link, ngx_array_t* const dst,
-                                      ngx_http_request_t* r) {
+// TODO(kumagi): Complex logic should be migrated to ngx_sxg_utils.c.
+// Extracts URL list `dst` from `link` like </foo.js>;rel="preload";as="script"
+// Returns length of non-preload header string.
+// If `dst` is NULL, it just calculate the length of estimatec
```
[the remark this answers is not in the document]
Comment (kumagi) [reply ngx_http_sxg_filter_module.c:339]: Done.

File: ngx_http_sxg_filter_module.c (hunk 7 above)
Comment (kumagi) [reply ngx_http_sxg_filter_module.c:336]: Yes, but I want separate it to refactoring work (in other patch).

File: ngx_http_sxg_filter_module.c (hunk 8 above)
Comment (kumagi) [reply ngx_http_sxg_filter_module.c:366]: I don't think that writing `'\0'` is required. But it maybe helpful for debug. Done.

File: ngx_http_sxg_filter_module.c [hunk 15]
```diff
@@ -303,38 +351,126 @@ static ngx_str_t extract_angled_url(char* str, size_t len) {
...
+  if (dst->data == NULL) {
+    return false;
+  }
+  dst->len = len;
+  memcpy(dst->data, src, len);
+  return true;
+}
+
+static bool set_accept_headers(ngx_http_request_t* req,
+                               ngx_subresource_t* target, const char* accept) {
```
[the remark this answers is not in the document]
Comment (kumagi) [reply ngx_http_sxg_filter_module.c:463]: Done.

File: ngx_http_sxg_filter_module.c [hunk 16]
```diff
@@ -345,16 +481,23 @@ static bool invoke_subrequests(ngx_str_t* link, ngx_http_request_t* req,
     }
     psr->handler = subresource_fetch_handler;
     psr->data = ctx;
+    ngx_log_error(NGX_LOG_DEBUG, req->connection->log, 0,
+                  "invoke request for: %V as %V", &entry[i].url, &entry[i].as);
+
+    if (!set_accept_headers(req, &entry[i], "*/*")) {
```
[the remark this answers is not in the document]
Comment (kumagi) [reply ngx_http_sxg_filter_module.c:495]: Done.

File: ngx_http_sxg_filter_module.c [hunk 17]
```diff
@@ -281,10 +281,28 @@ static ngx_int_t subresource_fetch_handler(ngx_http_request_t* req, void* data,
...
+    sxg_buffer_t url = sxg_empty_buffer();
     sxg_buffer_t integrity = sxg_empty_buffer();
     sxg_buffer_t new_header_entry = sxg_empty_buffer();
 
-    // Searche 'as' statement of original link header.
+    // Set URL which includes headers and parameters.
+    if (!sxg_write_string("https://", &url) ||
+        !buffer_write_str_t(&cscf->server_name, &url) ||
+        !buffer_write_str_t(&req->uri, &url)) {
+      sxg_buffer_release(&url);
```
[the remark this answers is not in the document]
Comment (kumagi) [reply ngx_http_sxg_filter_module.c:292]: Done.

File: ngx_http_sxg_filter_module.c [hunk 18]
```diff
@@ -281,10 +281,28 @@ static ngx_int_t subresource_fetch_handler(ngx_http_request_t* req, void* data,
...
+      --ctx->subresources;
+      return NGX_ERROR;
+    }
+    if (req->args.len > 0) {  // Append URL parameters.
+      if (!sxg_write_string("\?", &url) ||
+          !buffer_write_str_t(&req->args, &url)) {
+        sxg_buffer_release(&url);
```
[the remark this answers is not in the document]
Comment (kumagi) [reply ngx_http_sxg_filter_module.c:299]: Moved.

File: ngx_sxg_utils_test.cc [hunk 19]
```diff
@@ -86,6 +91,9 @@ TEST(NgxSxgUtilsTest, ParamIsPreload) {
   EXPECT_FALSE(ParamIsPreload("rel=\"\n \""));
   EXPECT_FALSE(ParamIsPreload("r"));
   EXPECT_FALSE(ParamIsPreload("rel=prepreload"));
+
+  // TODO: we should support this pattern.
+  // EXPECT_TRUE(ParamIsPreload("rel= preload"));
```
[the remark this answers is not in the document]
Comment (kumagi) [reply ngx_sxg_utils_test.cc:96]: specified `rel =` pattern.
