### PR TITLE
fix: fixed the method of determining if the content is fully loaded

### LINKED ISSUE #51: SXG response timeout when proxy_cache is enabled for subresources
Main SXG response is timeout when subresources are stored to the file in NGINX server with proxy_cache setting. This timeout issue only happens when there is a cache file of subresource in NGINX server and the modules sends a subrequest.

**How to reproduce:**

1. Prepare the nginx conf which enables proxy_cache for subresources (location `/static`)

```.nginxconf
proxy_cache_path /tmp/cache levels=1:2 keys_zone=nodejs:100m max_size=2g inactive=60m;

upstream node {
	server app:3000;
}

server {
  listen 80;
  listen 443 ssl;
  ssl_certificate /etc/nginx/server.crt;
  ssl_certificate_key /etc/nginx/server.key;
  root /var/www/html;
  index index.html index.htm index.nginx-debian.html;
  server_name example.com;

  sxg on;
  sxg_certificate     /etc/nginx/cert.pem;
  sxg_certificate_key /etc/nginx/priv.key;
  sxg_cert_url        https://sxg-sandbox.firebaseapp.com/cert.cbor;
  sxg_validity_url    https://example.com/validity/resource.msg;

  location = / {
    proxy_cache nodejs;
    proxy_cache_key $host$uri;
    proxy_cache_valid 200 60m;
    add_header X-Content-Type-Options nosniff;
    add_header Vary Accept;
    add_header Cache-Control "public, max-age=30";
    proxy_pass http://node;
  }

  location /static {
    proxy_cache nodejs;
    proxy_cache_key $host$uri;
    proxy_cache_valid 200 60m;
    add_header X-Content-Type-Options nosniff;
    add_header Vary Accept;
    proxy_pass http://node;
  }
}
```

2. Setup upstream server which returns subresoruces with cachablable header setting.

node.js server example:
```js
const express = require('express');
const path = require('path')

const PORT = 3000;
const HOST = '0.0.0.0';

const app = express();

// maxAge option is required because express server sets "Cache-Control: public, max-age=0" as a default, which leads NGINX not to cache response.
app.use('/static', express.static('public', {maxAge: 1000 * 60}))

app.get('/', (req, res) => {
  res.append('Link', '</static/style.css>;rel="preload";as="style"')
  res.sendFile(path.join(__dirname,'./public/index.html'), {cacheControl: false})
});

app.listen(PORT, HOST);
console.log(`Running on http://${HOST}:${PORT}`);
```

3. Run nginx and upstream application server
4. Store subresources to NGINX proxy cache.
```sh
// on your local machine
curl 'https://example.com/static/style.css'
// on NGINX server. Check if the cache file exists 
cat /tmp/cache/e/99/abda96163e15bae457c85f803036699e  | less
```
5. Send a request for SXG, the response won't be returned and timeout.
```
curl -H 'Accept: application/signed-exchange;v=b3' 'https://example.com' --output - -v
```

### PR DESCRIPTION
**Pull request by orisano**
fix #51
if the request hit the proxy cache, req->upstream->length is -1.

### CODE REVIEW

File: ngx_http_sxg_filter_module.c [hunk 1]
```diff
@@ -369,7 +369,12 @@ static ngx_int_t subresource_fetch_handler_impl(ngx_http_request_t* req,
     --ctx->subresources;
     return NGX_OK;
   }
-  if (req->out->buf->last - req->out->buf->pos == req->upstream->length) {
+  ngx_log_error(NGX_LOG_DEBUG, req->connection->log, 0,
+                "nginx-sxg-module: Subresource fetched. bytes=%l/%l",
+                req->out->buf->last - req->out->buf->pos,
+                req->upstream->length);
+  if (req->out->buf->last - req->out->buf->pos == req->upstream->length ||
+      req->upstream->length == -1) {
```
Comment (kumagi) [inline ngx_http_sxg_filter_module.c:377]: Can you put a short description comment for the case `upstream->length == -1` (maybe failed to load?)

Comment (orisano) [reply ngx_http_sxg_filter_module.c:379]: I added the description.

**Comment by kumagi** [comment]
Thank you!
