### PR TITLE
use requested path instead of resolved path for embedding URL

### LINKED ISSUE #74: Unexpected URLs in signed exchanges when using `try_files`
Hi! I'm leaving this issue here as there's a potential to improve the behavior of the module, however most importantly I wanted to leave somewhere a solution I found, so feel free to close if you don't see it relevant to fix. Other developers should be able to find it in closed issues as well.

A common way of implementing "clean URLs" (no trailing slashes) is to use `try_files` directive:

```
try_files $uri $uri/index.html =404;
```

The URL looks like this: `/foo/bar`, but the actual file lives in `/foo/bar/index.html`. When `try_files` is used alongside this module, the file path is in the signature instead of the requested URL: `/foo/bar/index.html`.

As a workaround, I'm now using `location` with a regular expression + `alias`:

```
location ~ ^/(.*) {
  rewrite ^/index(?:\.html|/)?$ / permanent;
  rewrite ^/(.*)/index(?:\.html|/)?$ /$1 permanent;
  rewrite ^/(.*)(?:\.html|/)$ /$1 permanent;

  alias /var/www/$1/index.html;
}
```

Result is the same when it comes to regular requests, however signatures contain a correct URL: `/foo/bar` with no `/index.html`.

### PR DESCRIPTION
**Pull request by kumagi**
fix #74 
But I'm not sure what URL should be embedded into SXG.

### CODE REVIEW

**Comment by sisidovski** [comment]
Since signing is done here, inner URL should be same as the passed URL from a client.

@kumagi , can you check if this URL works with this change?

https://style.nikkei.com/https%3A%2F%2Fimgix-proxy.n8s.jp%2Fcontent%2Fpic%2F20201029%2F96958A9F889DE4E7E1E2E0E6E5E2E0E0E3E2E0E2E0E2E2E2E2E2E2E2-DSXZZO6530272022102020000000-PB1-1.jpg?auto=format%2Ccompress&ch=Width%2CDPR&crop=focalpoint&fit=crop&fp-x=0.5&fp-y=0.5&h=419&ixlib=php-1.2.1&w=630&s=d87fda8bae60eb411876a0d472c160c1

I see an unexpectedly decoded URL in the inner URL field when signing with the current module version like this, and it doesn't work. This should be the same as above URL.

```
https://style.nikkei.com/https:/imgix-proxy.n8s.jp/content/pic/20201029/96958A9F889DE4E7E1E2E0E6E5E2E0E0E3E2E0E2E0E2E2E2E2E2E2E2-DSXZZO6530272022102020000000-PB1-1.jpg?auto=format%2Ccompress&ch=Width%2CDPR&crop=focalpoint&fit=crop&fp-x=0.5&fp-y=0.5&h=419&ixlib=php-1.2.1&w=630&s=d87fda8bae60eb411876a0d472c160c1
```

**Review by sisidovski — APPROVED** [review]
LGTM, but I'll defer it to @twifkak .

File: ngx_http_sxg_filter_module.c [hunk 1]
```diff
@@ -706,11 +708,11 @@ static char* construct_fallback_url(const ngx_http_request_t* req) {
 
   if (req->args.len > 0) {
     snprintf(fallback_url, fallback_url_length, "%s%s%.*s?%.*s", kHttpsPrefix,
-             host, path_length, req->uri.data, (int)req->args.len,
+             host, path_length, req->unparsed_uri.data, (int)req->args.len,
              req->args.data);
   } else {
     snprintf(fallback_url, fallback_url_length, "%s%s%.*s", kHttpsPrefix, host,
```
Comment (twifkak) [inline ngx_http_sxg_filter_module.c:714]: Is it possible to add support for unparsed_request_uri being an absolute URL? Or otherwise, just fall back to proxying the original content unsigned.

Per https://tools.ietf.org/html/rfc7230#section-5.3 we're supposed to support it, even though it'll rarely happen. So whatever's easiest, as long as it doesn't create something invalid like "https://https://site...".

**Review by twifkak — CHANGES_REQUESTED** [review]
Thanks for the fix! I think I found a few more things to change, PTAL.

File: ngx_http_sxg_filter_module.c (hunk 1 above)
Comment (twifkak) [reply ngx_http_sxg_filter_module.c:714]: BTW, this is not a blocker for me. If it's not easy to do something for this case, we can file a bug.

File: ngx_http_sxg_filter_module.c [hunk 2]
```diff
@@ -706,11 +708,11 @@ static char* construct_fallback_url(const ngx_http_request_t* req) {
 
   if (req->args.len > 0) {
```
[the remark this answers is not in the document]
Comment (kumagi) [reply ngx_http_sxg_filter_module.c]: Nice catch, I think I can remove this branch.

File: ngx_http_sxg_filter_module.c [hunk 3]
```diff
@@ -706,11 +708,11 @@ static char* construct_fallback_url(const ngx_http_request_t* req) {
...
     snprintf(fallback_url, fallback_url_length, "%s%s%.*s?%.*s", kHttpsPrefix,
-             host, path_length, req->uri.data, (int)req->args.len,
+             host, path_length, req->unparsed_uri.data, (int)req->args.len,
              req->args.data);
   } else {
     snprintf(fallback_url, fallback_url_length, "%s%s%.*s", kHttpsPrefix, host,
-             path_length, req->uri.data);
+             path_length, req->unparsed_uri.data);
```
[the remark this answers is not in the document]
Comment (kumagi) [reply ngx_http_sxg_filter_module.c]: We can eliminate `path_length` if my understanding is correct. It became very simplified one.

File: ngx_http_sxg_filter_module.c (hunk 1 above)
Comment (kumagi) [reply ngx_http_sxg_filter_module.c]: Sorry, I'm not sure what is specified as `unparsed_request_uri`.
Is that mean `req->uparsed_uri` contains `https://` started string? If so, can it be avoided with something like `if (memcmp(uri, "https://",..) == 0` ?
That should be fixed eventually but I think that should be done with another patch. Can you bug another issue?

**Comment by Jxck** [comment]
I'm not a right person to review this.
I'll defer to @twifkak too.

**Review by twifkak — APPROVED** [review]

File: ngx_http_sxg_filter_module.c (hunk 1 above)
Comment (twifkak) [reply ngx_http_sxg_filter_module.c]: Yes, that's the idea. Filed #79.
